//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kunde()
        {
            this.udlejning = new HashSet<udlejning>();
        }
    
        public int KundeNummer { get; set; }
        public string Navn { get; set; }
        public string Addresse { get; set; }
        public string EMail { get; set; }
        public string Brugernavn { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<udlejning> udlejning { get; set; }
    }
}
