//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produkter()
        {
            this.udlejning = new HashSet<udlejning>();
        }
    
        public int ProduktID { get; set; }
        public string Navn { get; set; }
        public Nullable<double> Doegnpris { get; set; }
        public Nullable<double> Depositum { get; set; }
        public string Beskrivelse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<udlejning> udlejning { get; set; }
    }
}
