//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class udlejning
    {
        public int UdlejningsNummer { get; set; }
        public Nullable<int> KundeNr { get; set; }
        public Nullable<int> PID { get; set; }
        public string ProduktStatus { get; set; }
        public string Afhentningstidspunkt { get; set; }
        public Nullable<int> AntalDoegn { get; set; }
    
        public virtual kunde kunde { get; set; }
        public virtual produkter produkter { get; set; }
    }
}
