//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EksamensOpgave_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produkter()
        {
            this.bydning = new HashSet<bydning>();
        }
    
        public int ProduktID { get; set; }
        public string MetalType { get; set; }
        public string Maengde { get; set; }
        public Nullable<double> Bud { get; set; }
        public Nullable<System.DateTime> Auktionsfrist { get; set; }
        public Nullable<int> KundeNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bydning> bydning { get; set; }
        public virtual kunde kunde { get; set; }
    }
}
